apiVersion: v1
kind: Service
metadata:
  name: securepen-backend-service
  labels:
    app: securepen
    tier: backend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
spec:
  selector:
    app: securepen
    tier: backend
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
